// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Prefer environment variables if provided, with a fallback to the generated values
const SUPABASE_URL = (import.meta as any).env?.VITE_SUPABASE_URL || "https://wjrnqkadulzitspraslg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = (import.meta as any).env?.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indqcm5xa2FkdWx6aXRzcHJhc2xnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNzk4MTUsImV4cCI6MjA2NDY1NTgxNX0.qAevWxR_s2y39g4LEQ__07PhfpkoBrNH4ucbXx4cBhI";

if (!(import.meta as any).env?.VITE_SUPABASE_URL || !(import.meta as any).env?.VITE_SUPABASE_ANON_KEY) {
  // eslint-disable-next-line no-console
  console.warn(
    '[Supabase] Using default generated URL/key. Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in your .env.local to point to your own project.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});